In [14]:
#Lung_Cancer_prediction Using SVM algorithm 
import numpy as np 
import pandas as pd
df=pd.read_csv('/home/user/d_set/lung_cancer_.csv')
df.head()
df1=df.drop(['Name','Surname'],axis=1)

In [16]:
x=df1.iloc[:,:-1].values
y=df1.iloc[:,-1].values
print(x)
print(y)


[[35  3  5  4]
 [27 20  2  5]
 [30  0  5  2]
 [28  0  8  1]
 [68  4  5  6]
 [34  0 10  0]
 [58 15 10  0]
 [22 12  5  2]
 [45  2  6  0]
 [52 18  4  5]
 [33  4  8  0]
 [18 10  6  3]
 [25  2  5  1]
 [28 20  2  8]
 [34 25  4  8]
 [39 18  8  1]
 [42 22  3  5]
 [19 12  8  0]
 [62  5  4  3]
 [73 10  7  6]
 [55 15  1  3]
 [33  8  8  1]
 [22 20  6  2]
 [44  5  8  1]
 [77  3  2  6]
 [21 20  5  3]
 [37 15  6  2]
 [34 12  8  0]
 [55 20  1  4]
 [40 20  2  7]
 [36 13  5  2]
 [56 20  3  3]
 [47 15  1  8]
 [62 25  3  4]
 [26 10  7  2]
 [25 20  8  2]
 [59 20  3  4]
 [62 15  5  5]
 [33 25  8  2]
 [37 10  5  3]
 [50 20  2  4]
 [47 12  8  0]
 [69 20  5  4]
 [63 20  4  5]
 [39 15  7  2]
 [21 20  8  3]
 [31 20  9  4]
 [28 10  4  1]
 [53 20  6  3]
 [62 20  5  6]
 [42 12  6  2]
 [44 30  1  6]
 [26 34  1  8]
 [35 20  5  1]
 [26 13  6  1]
 [77 20  5  4]
 [75 15  3  5]
 [43 30  3  8]
 [51 25  9  0]]
[1 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1 1 0 1 1 1 0 0 1
 1 0 0 1 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)

In [20]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [21]:
from sklearn.svm import SVC
classifier=SVC()
classifier.fit(x_train,y_train)

SVC()

In [22]:
y_pred=classifier.predict(x_test)

In [24]:
print(classifier.predict([[23,1,5,6]])) 
#as per the input given by the user the patient has the possibility of lung cancer

[1]


In [25]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
r1=classification_report(y_test,y_pred)
print(r1)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00         7

    accuracy                           1.00        18
   macro avg       1.00      1.00      1.00        18
weighted avg       1.00      1.00      1.00        18



In [26]:
r2=confusion_matrix(y_test,y_pred)
print(r2)

[[11  0]
 [ 0  7]]


In [27]:
r3=accuracy_score(y_test,y_pred)
print(r3)

1.0
