In [1]:
import numpy as np 
import pandas as pd 
df=pd.read_csv("/home/user/d_set/lung_cancer_.csv")
df.head()

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1

In [2]:
df1=df.drop(['Name','Surname'],axis=1)
# print(df1)
x=df1.iloc[:,:-1].values
y=df1.iloc[:,-1].values
print(x)
print(y)

[[35  3  5  4]
 [27 20  2  5]
 [30  0  5  2]
 [28  0  8  1]
 [68  4  5  6]
 [34  0 10  0]
 [58 15 10  0]
 [22 12  5  2]
 [45  2  6  0]
 [52 18  4  5]
 [33  4  8  0]
 [18 10  6  3]
 [25  2  5  1]
 [28 20  2  8]
 [34 25  4  8]
 [39 18  8  1]
 [42 22  3  5]
 [19 12  8  0]
 [62  5  4  3]
 [73 10  7  6]
 [55 15  1  3]
 [33  8  8  1]
 [22 20  6  2]
 [44  5  8  1]
 [77  3  2  6]
 [21 20  5  3]
 [37 15  6  2]
 [34 12  8  0]
 [55 20  1  4]
 [40 20  2  7]
 [36 13  5  2]
 [56 20  3  3]
 [47 15  1  8]
 [62 25  3  4]
 [26 10  7  2]
 [25 20  8  2]
 [59 20  3  4]
 [62 15  5  5]
 [33 25  8  2]
 [37 10  5  3]
 [50 20  2  4]
 [47 12  8  0]
 [69 20  5  4]
 [63 20  4  5]
 [39 15  7  2]
 [21 20  8  3]
 [31 20  9  4]
 [28 10  4  1]
 [53 20  6  3]
 [62 20  5  6]
 [42 12  6  2]
 [44 30  1  6]
 [26 34  1  8]
 [35 20  5  1]
 [26 13  6  1]
 [77 20  5  4]
 [75 15  3  5]
 [43 30  3  8]
 [51 25  9  0]]
[1 1 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 0 1 1 1 0 0 0 1 0 0 0 1 1 0 1 1 1 0 0 1
 1 0 0 1 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1 

In [3]:
from collections import Counter
print("the number of classes",Counter(y))

the number of classes Counter({0: 31, 1: 28})


In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=55)
print(x_test)

[[47 15  1  8]
 [50 20  2  4]
 [39 18  8  1]
 [58 15 10  0]
 [73 10  7  6]
 [28  0  8  1]
 [33  8  8  1]
 [68  4  5  6]
 [34  0 10  0]
 [75 15  3  5]
 [21 20  5  3]
 [33 25  8  2]
 [30  0  5  2]
 [18 10  6  3]
 [47 12  8  0]
 [39 15  7  2]
 [55 20  1  4]
 [22 20  6  2]]


In [24]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
print(df.describe())
# minmax scaler
# from sklearn import preprocessing
# import numpy as np
# min_max_scaler=preprocessing.MinMaxScaler()
# x_train=min_max_scaler.fit
# y_train=min_max_scaler.fit
# print(x_train)

             Age     Smokes      AreaQ     Alkhol     Result
count  59.000000  59.000000  59.000000  59.000000  59.000000
mean   42.627119  15.067797   5.203390   3.237288   0.474576
std    16.235230   7.984607   2.461984   2.380517   0.503640
min    18.000000   0.000000   1.000000   0.000000   0.000000
25%    29.000000  10.000000   3.000000   1.000000   0.000000
50%    39.000000  15.000000   5.000000   3.000000   0.000000
75%    55.000000  20.000000   7.500000   5.000000   1.000000
max    77.000000  34.000000  10.000000   8.000000   1.000000


In [25]:
# from sklearn.neighbors import KNeighborsClassifier
# classifier=KNeighborsClassifier(n_neighbors=5)
# classifier.fit(x_train,y_train)
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [26]:
y_predict=classifier.predict(x_test)

In [27]:
print(classifier.predict([[23,5,3,6]]))
# zero=no
# one=yes

[1]


In [28]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
r1=accuracy_score(y_test,y_predict)
print(r1)

1.0


In [29]:
r2=classification_report(y_test,y_predict)
print(r2)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         6

    accuracy                           1.00        18
   macro avg       1.00      1.00      1.00        18
weighted avg       1.00      1.00      1.00        18

